server:
  port: ${PORT:8081}

spring:
  application:
    name: service-processor
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

aws:
  region: us-east-1
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:https://sqs.us-east-1.amazonaws.com/828818793977/uploads-events}