apiVersion: v1
kind: Service
metadata:
  name: service-processor
spec:
  type: LoadBalancer
  selector:
    app: service-processor-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local